# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.adminv1_api_endpoints.add_application import AddApplication
from edu_sharing_client.api.adminv1_api_endpoints.add_application1 import AddApplication1
from edu_sharing_client.api.adminv1_api_endpoints.add_toolpermission import AddToolpermission
from edu_sharing_client.api.adminv1_api_endpoints.apply_template import ApplyTemplate
from edu_sharing_client.api.adminv1_api_endpoints.cancel_job import CancelJob
from edu_sharing_client.api.adminv1_api_endpoints.change_logging import ChangeLogging
from edu_sharing_client.api.adminv1_api_endpoints.clear_cache import ClearCache
from edu_sharing_client.api.adminv1_api_endpoints.delete_person import DeletePerson
from edu_sharing_client.api.adminv1_api_endpoints.export_by_lucene import ExportByLucene
from edu_sharing_client.api.adminv1_api_endpoints.export_lom import ExportLom
from edu_sharing_client.api.adminv1_api_endpoints.get_all_jobs import GetAllJobs
from edu_sharing_client.api.adminv1_api_endpoints.get_all_toolpermissions import GetAllToolpermissions
from edu_sharing_client.api.adminv1_api_endpoints.get_application_xml import GetApplicationXml
from edu_sharing_client.api.adminv1_api_endpoints.get_applications import GetApplications
from edu_sharing_client.api.adminv1_api_endpoints.get_cache_entries import GetCacheEntries
from edu_sharing_client.api.adminv1_api_endpoints.get_cache_info import GetCacheInfo
from edu_sharing_client.api.adminv1_api_endpoints.get_catalina_out import GetCatalinaOut
from edu_sharing_client.api.adminv1_api_endpoints.get_cluster import GetCluster
from edu_sharing_client.api.adminv1_api_endpoints.get_clusters import GetClusters
from edu_sharing_client.api.adminv1_api_endpoints.get_config import GetConfig
from edu_sharing_client.api.adminv1_api_endpoints.get_config_file import GetConfigFile
from edu_sharing_client.api.adminv1_api_endpoints.get_global_groups import GetGlobalGroups
from edu_sharing_client.api.adminv1_api_endpoints.get_jobs import GetJobs
from edu_sharing_client.api.adminv1_api_endpoints.get_lightbend_config import GetLightbendConfig
from edu_sharing_client.api.adminv1_api_endpoints.get_oai_classes import GetOaiClasses
from edu_sharing_client.api.adminv1_api_endpoints.get_property_to_mds import GetPropertyToMds
from edu_sharing_client.api.adminv1_api_endpoints.get_statistics import GetStatistics
from edu_sharing_client.api.adminv1_api_endpoints.import_collections import ImportCollections
from edu_sharing_client.api.adminv1_api_endpoints.import_excel import ImportExcel
from edu_sharing_client.api.adminv1_api_endpoints.import_oai import ImportOai
from edu_sharing_client.api.adminv1_api_endpoints.import_oai_xml import ImportOaiXml
from edu_sharing_client.api.adminv1_api_endpoints.refresh_app_info import RefreshAppInfo
from edu_sharing_client.api.adminv1_api_endpoints.refresh_cache import RefreshCache
from edu_sharing_client.api.adminv1_api_endpoints.refresh_edu_group_cache import RefreshEduGroupCache
from edu_sharing_client.api.adminv1_api_endpoints.remove_application import RemoveApplication
from edu_sharing_client.api.adminv1_api_endpoints.remove_cache_entry import RemoveCacheEntry
from edu_sharing_client.api.adminv1_api_endpoints.remove_oai_imports import RemoveOaiImports
from edu_sharing_client.api.adminv1_api_endpoints.search_by_elastic_dsl import SearchByElasticDsl
from edu_sharing_client.api.adminv1_api_endpoints.search_by_lucene import SearchByLucene
from edu_sharing_client.api.adminv1_api_endpoints.server_update_list import ServerUpdateList
from edu_sharing_client.api.adminv1_api_endpoints.server_update_list1 import ServerUpdateList1
from edu_sharing_client.api.adminv1_api_endpoints.set_config import SetConfig
from edu_sharing_client.api.adminv1_api_endpoints.set_toolpermissions import SetToolpermissions
from edu_sharing_client.api.adminv1_api_endpoints.start_job import StartJob
from edu_sharing_client.api.adminv1_api_endpoints.start_job_sync import StartJobSync
from edu_sharing_client.api.adminv1_api_endpoints.switch_authority import SwitchAuthority
from edu_sharing_client.api.adminv1_api_endpoints.test_mail import TestMail
from edu_sharing_client.api.adminv1_api_endpoints.update_application_xml import UpdateApplicationXml
from edu_sharing_client.api.adminv1_api_endpoints.update_config_file import UpdateConfigFile
from edu_sharing_client.api.adminv1_api_endpoints.upload_temp import UploadTemp


class ADMINV1Api(
    AddApplication,
    AddApplication1,
    AddToolpermission,
    ApplyTemplate,
    CancelJob,
    ChangeLogging,
    ClearCache,
    DeletePerson,
    ExportByLucene,
    ExportLom,
    GetAllJobs,
    GetAllToolpermissions,
    GetApplicationXml,
    GetApplications,
    GetCacheEntries,
    GetCacheInfo,
    GetCatalinaOut,
    GetCluster,
    GetClusters,
    GetConfig,
    GetConfigFile,
    GetGlobalGroups,
    GetJobs,
    GetLightbendConfig,
    GetOaiClasses,
    GetPropertyToMds,
    GetStatistics,
    ImportCollections,
    ImportExcel,
    ImportOai,
    ImportOaiXml,
    RefreshAppInfo,
    RefreshCache,
    RefreshEduGroupCache,
    RemoveApplication,
    RemoveCacheEntry,
    RemoveOaiImports,
    SearchByElasticDsl,
    SearchByLucene,
    ServerUpdateList,
    ServerUpdateList1,
    SetConfig,
    SetToolpermissions,
    StartJob,
    StartJobSync,
    SwitchAuthority,
    TestMail,
    UpdateApplicationXml,
    UpdateConfigFile,
    UploadTemp,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
