# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.authenticationv1_api_endpoints.authenticate import Authenticate
from edu_sharing_client.api.authenticationv1_api_endpoints.has_access_to_scope import HasAccessToScope
from edu_sharing_client.api.authenticationv1_api_endpoints.login import Login
from edu_sharing_client.api.authenticationv1_api_endpoints.login_to_scope import LoginToScope
from edu_sharing_client.api.authenticationv1_api_endpoints.logout import Logout


class AUTHENTICATIONV1Api(
    Authenticate,
    HasAccessToScope,
    Login,
    LoginToScope,
    Logout,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
