# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.collectionv1_api_endpoints.add_feedback_to_collection import AddFeedbackToCollection
from edu_sharing_client.api.collectionv1_api_endpoints.add_to_collection import AddToCollection
from edu_sharing_client.api.collectionv1_api_endpoints.change_icon_of_collection import ChangeIconOfCollection
from edu_sharing_client.api.collectionv1_api_endpoints.create_collection import CreateCollection
from edu_sharing_client.api.collectionv1_api_endpoints.delete_collection import DeleteCollection
from edu_sharing_client.api.collectionv1_api_endpoints.delete_from_collection import DeleteFromCollection
from edu_sharing_client.api.collectionv1_api_endpoints.get_collection import GetCollection
from edu_sharing_client.api.collectionv1_api_endpoints.get_collections_containing_proposals import GetCollectionsContainingProposals
from edu_sharing_client.api.collectionv1_api_endpoints.get_collections_proposals import GetCollectionsProposals
from edu_sharing_client.api.collectionv1_api_endpoints.get_collections_references import GetCollectionsReferences
from edu_sharing_client.api.collectionv1_api_endpoints.get_collections_subcollections import GetCollectionsSubcollections
from edu_sharing_client.api.collectionv1_api_endpoints.get_feedback_of_collection import GetFeedbackOfCollection
from edu_sharing_client.api.collectionv1_api_endpoints.remove_icon_of_collection import RemoveIconOfCollection
from edu_sharing_client.api.collectionv1_api_endpoints.search_collections import SearchCollections
from edu_sharing_client.api.collectionv1_api_endpoints.set_collection_order import SetCollectionOrder
from edu_sharing_client.api.collectionv1_api_endpoints.set_pinned_collections import SetPinnedCollections
from edu_sharing_client.api.collectionv1_api_endpoints.update_collection import UpdateCollection


class COLLECTIONV1Api(
    AddFeedbackToCollection,
    AddToCollection,
    ChangeIconOfCollection,
    CreateCollection,
    DeleteCollection,
    DeleteFromCollection,
    GetCollection,
    GetCollectionsContainingProposals,
    GetCollectionsProposals,
    GetCollectionsReferences,
    GetCollectionsSubcollections,
    GetFeedbackOfCollection,
    RemoveIconOfCollection,
    SearchCollections,
    SetCollectionOrder,
    SetPinnedCollections,
    UpdateCollection,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
