# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.configv1_api_endpoints.get_config1 import GetConfig1
from edu_sharing_client.api.configv1_api_endpoints.get_dynamic_value import GetDynamicValue
from edu_sharing_client.api.configv1_api_endpoints.get_language import GetLanguage
from edu_sharing_client.api.configv1_api_endpoints.get_language_defaults import GetLanguageDefaults
from edu_sharing_client.api.configv1_api_endpoints.get_variables import GetVariables
from edu_sharing_client.api.configv1_api_endpoints.set_dynamic_value import SetDynamicValue


class CONFIGV1Api(
    GetConfig1,
    GetDynamicValue,
    GetLanguage,
    GetLanguageDefaults,
    GetVariables,
    SetDynamicValue,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
