# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.iamv1_api_endpoints.add_membership import AddMembership
from edu_sharing_client.api.iamv1_api_endpoints.add_node_list import AddNodeList
from edu_sharing_client.api.iamv1_api_endpoints.change_group_profile import ChangeGroupProfile
from edu_sharing_client.api.iamv1_api_endpoints.change_user_avatar import ChangeUserAvatar
from edu_sharing_client.api.iamv1_api_endpoints.change_user_password import ChangeUserPassword
from edu_sharing_client.api.iamv1_api_endpoints.change_user_profile import ChangeUserProfile
from edu_sharing_client.api.iamv1_api_endpoints.confirm_signup import ConfirmSignup
from edu_sharing_client.api.iamv1_api_endpoints.create_group import CreateGroup
from edu_sharing_client.api.iamv1_api_endpoints.create_user import CreateUser
from edu_sharing_client.api.iamv1_api_endpoints.delete_group import DeleteGroup
from edu_sharing_client.api.iamv1_api_endpoints.delete_membership import DeleteMembership
from edu_sharing_client.api.iamv1_api_endpoints.delete_user import DeleteUser
from edu_sharing_client.api.iamv1_api_endpoints.get_group import GetGroup
from edu_sharing_client.api.iamv1_api_endpoints.get_membership import GetMembership
from edu_sharing_client.api.iamv1_api_endpoints.get_node_list import GetNodeList
from edu_sharing_client.api.iamv1_api_endpoints.get_preferences import GetPreferences
from edu_sharing_client.api.iamv1_api_endpoints.get_profile_settings import GetProfileSettings
from edu_sharing_client.api.iamv1_api_endpoints.get_recently_invited import GetRecentlyInvited
from edu_sharing_client.api.iamv1_api_endpoints.get_subgroup_by_type import GetSubgroupByType
from edu_sharing_client.api.iamv1_api_endpoints.get_user import GetUser
from edu_sharing_client.api.iamv1_api_endpoints.get_user_groups import GetUserGroups
from edu_sharing_client.api.iamv1_api_endpoints.get_user_stats import GetUserStats
from edu_sharing_client.api.iamv1_api_endpoints.reject_signup import RejectSignup
from edu_sharing_client.api.iamv1_api_endpoints.remove_node_list import RemoveNodeList
from edu_sharing_client.api.iamv1_api_endpoints.remove_user_avatar import RemoveUserAvatar
from edu_sharing_client.api.iamv1_api_endpoints.search_authorities import SearchAuthorities
from edu_sharing_client.api.iamv1_api_endpoints.search_groups import SearchGroups
from edu_sharing_client.api.iamv1_api_endpoints.search_user import SearchUser
from edu_sharing_client.api.iamv1_api_endpoints.set_preferences import SetPreferences
from edu_sharing_client.api.iamv1_api_endpoints.set_profile_settings import SetProfileSettings
from edu_sharing_client.api.iamv1_api_endpoints.signup_group import SignupGroup
from edu_sharing_client.api.iamv1_api_endpoints.signup_group_details import SignupGroupDetails
from edu_sharing_client.api.iamv1_api_endpoints.signup_group_list import SignupGroupList
from edu_sharing_client.api.iamv1_api_endpoints.update_user_status import UpdateUserStatus


class IAMV1Api(
    AddMembership,
    AddNodeList,
    ChangeGroupProfile,
    ChangeUserAvatar,
    ChangeUserPassword,
    ChangeUserProfile,
    ConfirmSignup,
    CreateGroup,
    CreateUser,
    DeleteGroup,
    DeleteMembership,
    DeleteUser,
    GetGroup,
    GetMembership,
    GetNodeList,
    GetPreferences,
    GetProfileSettings,
    GetRecentlyInvited,
    GetSubgroupByType,
    GetUser,
    GetUserGroups,
    GetUserStats,
    RejectSignup,
    RemoveNodeList,
    RemoveUserAvatar,
    SearchAuthorities,
    SearchGroups,
    SearchUser,
    SetPreferences,
    SetProfileSettings,
    SignupGroup,
    SignupGroupDetails,
    SignupGroupList,
    UpdateUserStatus,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
