# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.mdsv1_api_endpoints.get_metadata_set import GetMetadataSet
from edu_sharing_client.api.mdsv1_api_endpoints.get_metadata_sets import GetMetadataSets
from edu_sharing_client.api.mdsv1_api_endpoints.get_values import GetValues
from edu_sharing_client.api.mdsv1_api_endpoints.get_values4_keys import GetValues4Keys
from edu_sharing_client.api.mdsv1_api_endpoints.suggest_value import SuggestValue


class MDSV1Api(
    GetMetadataSet,
    GetMetadataSets,
    GetValues,
    GetValues4Keys,
    SuggestValue,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
