# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.mediacenterv1_api_endpoints.add_mediacenter_group import AddMediacenterGroup
from edu_sharing_client.api.mediacenterv1_api_endpoints.create_mediacenter import CreateMediacenter
from edu_sharing_client.api.mediacenterv1_api_endpoints.delete_mediacenter import DeleteMediacenter
from edu_sharing_client.api.mediacenterv1_api_endpoints.edit_mediacenter import EditMediacenter
from edu_sharing_client.api.mediacenterv1_api_endpoints.get_mediacenter_groups import GetMediacenterGroups
from edu_sharing_client.api.mediacenterv1_api_endpoints.get_mediacenter_licensed_nodes import GetMediacenterLicensedNodes
from edu_sharing_client.api.mediacenterv1_api_endpoints.get_mediacenters import GetMediacenters
from edu_sharing_client.api.mediacenterv1_api_endpoints.import_mc_org_connections import ImportMcOrgConnections
from edu_sharing_client.api.mediacenterv1_api_endpoints.import_mediacenters import ImportMediacenters
from edu_sharing_client.api.mediacenterv1_api_endpoints.import_organisations import ImportOrganisations
from edu_sharing_client.api.mediacenterv1_api_endpoints.remove_mediacenter_group import RemoveMediacenterGroup


class MEDIACENTERV1Api(
    AddMediacenterGroup,
    CreateMediacenter,
    DeleteMediacenter,
    EditMediacenter,
    GetMediacenterGroups,
    GetMediacenterLicensedNodes,
    GetMediacenters,
    ImportMcOrgConnections,
    ImportMediacenters,
    ImportOrganisations,
    RemoveMediacenterGroup,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
