# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.nodev1_api_endpoints.add_aspects import AddAspects
from edu_sharing_client.api.nodev1_api_endpoints.add_workflow_history import AddWorkflowHistory
from edu_sharing_client.api.nodev1_api_endpoints.change_content import ChangeContent
from edu_sharing_client.api.nodev1_api_endpoints.change_content_as_text import ChangeContentAsText
from edu_sharing_client.api.nodev1_api_endpoints.change_metadata import ChangeMetadata
from edu_sharing_client.api.nodev1_api_endpoints.change_metadata_with_versioning import ChangeMetadataWithVersioning
from edu_sharing_client.api.nodev1_api_endpoints.change_preview import ChangePreview
from edu_sharing_client.api.nodev1_api_endpoints.change_template_metadata import ChangeTemplateMetadata
from edu_sharing_client.api.nodev1_api_endpoints.create_child import CreateChild
from edu_sharing_client.api.nodev1_api_endpoints.create_child_by_copying import CreateChildByCopying
from edu_sharing_client.api.nodev1_api_endpoints.create_child_by_moving import CreateChildByMoving
from edu_sharing_client.api.nodev1_api_endpoints.create_fork_of_node import CreateForkOfNode
from edu_sharing_client.api.nodev1_api_endpoints.create_share import CreateShare
from edu_sharing_client.api.nodev1_api_endpoints.delete import Delete
from edu_sharing_client.api.nodev1_api_endpoints.delete_preview import DeletePreview
from edu_sharing_client.api.nodev1_api_endpoints.get_assocs import GetAssocs
from edu_sharing_client.api.nodev1_api_endpoints.get_children import GetChildren
from edu_sharing_client.api.nodev1_api_endpoints.get_metadata import GetMetadata
from edu_sharing_client.api.nodev1_api_endpoints.get_nodes import GetNodes
from edu_sharing_client.api.nodev1_api_endpoints.get_notify_list import GetNotifyList
from edu_sharing_client.api.nodev1_api_endpoints.get_parents import GetParents
from edu_sharing_client.api.nodev1_api_endpoints.get_permission import GetPermission
from edu_sharing_client.api.nodev1_api_endpoints.get_published_copies import GetPublishedCopies
from edu_sharing_client.api.nodev1_api_endpoints.get_shares import GetShares
from edu_sharing_client.api.nodev1_api_endpoints.get_template_metadata import GetTemplateMetadata
from edu_sharing_client.api.nodev1_api_endpoints.get_text_content import GetTextContent
from edu_sharing_client.api.nodev1_api_endpoints.get_version_metadata import GetVersionMetadata
from edu_sharing_client.api.nodev1_api_endpoints.get_versions import GetVersions
from edu_sharing_client.api.nodev1_api_endpoints.get_workflow_history import GetWorkflowHistory
from edu_sharing_client.api.nodev1_api_endpoints.has_permission import HasPermission
from edu_sharing_client.api.nodev1_api_endpoints.import_node import ImportNode
from edu_sharing_client.api.nodev1_api_endpoints.islocked import Islocked
from edu_sharing_client.api.nodev1_api_endpoints.prepare_usage import PrepareUsage
from edu_sharing_client.api.nodev1_api_endpoints.publish_copy import PublishCopy
from edu_sharing_client.api.nodev1_api_endpoints.remove_share import RemoveShare
from edu_sharing_client.api.nodev1_api_endpoints.report_node import ReportNode
from edu_sharing_client.api.nodev1_api_endpoints.revert_version import RevertVersion
from edu_sharing_client.api.nodev1_api_endpoints.set_owner import SetOwner
from edu_sharing_client.api.nodev1_api_endpoints.set_permission import SetPermission
from edu_sharing_client.api.nodev1_api_endpoints.set_property import SetProperty
from edu_sharing_client.api.nodev1_api_endpoints.store_x_api_data import StoreXApiData
from edu_sharing_client.api.nodev1_api_endpoints.unlock import Unlock
from edu_sharing_client.api.nodev1_api_endpoints.update_share import UpdateShare


class NODEV1Api(
    AddAspects,
    AddWorkflowHistory,
    ChangeContent,
    ChangeContentAsText,
    ChangeMetadata,
    ChangeMetadataWithVersioning,
    ChangePreview,
    ChangeTemplateMetadata,
    CreateChild,
    CreateChildByCopying,
    CreateChildByMoving,
    CreateForkOfNode,
    CreateShare,
    Delete,
    DeletePreview,
    GetAssocs,
    GetChildren,
    GetMetadata,
    GetNodes,
    GetNotifyList,
    GetParents,
    GetPermission,
    GetPublishedCopies,
    GetShares,
    GetTemplateMetadata,
    GetTextContent,
    GetVersionMetadata,
    GetVersions,
    GetWorkflowHistory,
    HasPermission,
    ImportNode,
    Islocked,
    PrepareUsage,
    PublishCopy,
    RemoveShare,
    ReportNode,
    RevertVersion,
    SetOwner,
    SetPermission,
    SetProperty,
    StoreXApiData,
    Unlock,
    UpdateShare,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
