# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.ratingv1_api_endpoints.add_or_update_rating import AddOrUpdateRating
from edu_sharing_client.api.ratingv1_api_endpoints.delete_rating import DeleteRating


class RATINGV1Api(
    AddOrUpdateRating,
    DeleteRating,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
