# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.registerv1_api_endpoints.activate import Activate
from edu_sharing_client.api.registerv1_api_endpoints.mail_exists import MailExists
from edu_sharing_client.api.registerv1_api_endpoints.recover_password import RecoverPassword
from edu_sharing_client.api.registerv1_api_endpoints.register import Register
from edu_sharing_client.api.registerv1_api_endpoints.resend_mail import ResendMail
from edu_sharing_client.api.registerv1_api_endpoints.reset_password import ResetPassword


class REGISTERV1Api(
    Activate,
    MailExists,
    RecoverPassword,
    Register,
    ResendMail,
    ResetPassword,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
