# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.renderingv1_api_endpoints.get_details_snippet import GetDetailsSnippet
from edu_sharing_client.api.renderingv1_api_endpoints.get_details_snippet_with_parameters import GetDetailsSnippetWithParameters


class RENDERINGV1Api(
    GetDetailsSnippet,
    GetDetailsSnippetWithParameters,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
