# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.searchv1_api_endpoints.get_metdata import GetMetdata
from edu_sharing_client.api.searchv1_api_endpoints.get_relevant_nodes import GetRelevantNodes
from edu_sharing_client.api.searchv1_api_endpoints.load_save_search import LoadSaveSearch
from edu_sharing_client.api.searchv1_api_endpoints.save_search import SaveSearch
from edu_sharing_client.api.searchv1_api_endpoints.search import Search
from edu_sharing_client.api.searchv1_api_endpoints.search_by_property import SearchByProperty
from edu_sharing_client.api.searchv1_api_endpoints.search_contributor import SearchContributor
from edu_sharing_client.api.searchv1_api_endpoints.search_facets import SearchFacets
from edu_sharing_client.api.searchv1_api_endpoints.search_fingerprint import SearchFingerprint


class SEARCHV1Api(
    GetMetdata,
    GetRelevantNodes,
    LoadSaveSearch,
    SaveSearch,
    Search,
    SearchByProperty,
    SearchContributor,
    SearchFacets,
    SearchFingerprint,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
