# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.statisticv1_api_endpoints.get import Get
from edu_sharing_client.api.statisticv1_api_endpoints.get_global_statistics import GetGlobalStatistics
from edu_sharing_client.api.statisticv1_api_endpoints.get_node_data import GetNodeData
from edu_sharing_client.api.statisticv1_api_endpoints.get_nodes_altered_in_range import GetNodesAlteredInRange
from edu_sharing_client.api.statisticv1_api_endpoints.get_statistics_node import GetStatisticsNode
from edu_sharing_client.api.statisticv1_api_endpoints.get_statistics_user import GetStatisticsUser


class STATISTICV1Api(
    Get,
    GetGlobalStatistics,
    GetNodeData,
    GetNodesAlteredInRange,
    GetStatisticsNode,
    GetStatisticsUser,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
