# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.streamv1_api_endpoints.add_entry import AddEntry
from edu_sharing_client.api.streamv1_api_endpoints.can_access import CanAccess
from edu_sharing_client.api.streamv1_api_endpoints.delete_entry import DeleteEntry
from edu_sharing_client.api.streamv1_api_endpoints.get_property_values import GetPropertyValues
from edu_sharing_client.api.streamv1_api_endpoints.search1 import Search1
from edu_sharing_client.api.streamv1_api_endpoints.update_entry import UpdateEntry


class STREAMV1Api(
    AddEntry,
    CanAccess,
    DeleteEntry,
    GetPropertyValues,
    Search1,
    UpdateEntry,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
