# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.toolv1_api_endpoints.create_tool_defintition import CreateToolDefintition
from edu_sharing_client.api.toolv1_api_endpoints.create_tool_instance import CreateToolInstance
from edu_sharing_client.api.toolv1_api_endpoints.create_tool_object import CreateToolObject
from edu_sharing_client.api.toolv1_api_endpoints.get_all_tool_definitions import GetAllToolDefinitions
from edu_sharing_client.api.toolv1_api_endpoints.get_instance import GetInstance
from edu_sharing_client.api.toolv1_api_endpoints.get_instances import GetInstances


class TOOLV1Api(
    CreateToolDefintition,
    CreateToolInstance,
    CreateToolObject,
    GetAllToolDefinitions,
    GetInstance,
    GetInstances,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
