# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

from edu_sharing_client.api_client import ApiClient
from edu_sharing_client.api.usagev1_api_endpoints.delete_usage import DeleteUsage
from edu_sharing_client.api.usagev1_api_endpoints.get_usages import GetUsages
from edu_sharing_client.api.usagev1_api_endpoints.get_usages1 import GetUsages1
from edu_sharing_client.api.usagev1_api_endpoints.get_usages_by_course import GetUsagesByCourse
from edu_sharing_client.api.usagev1_api_endpoints.get_usages_by_node import GetUsagesByNode
from edu_sharing_client.api.usagev1_api_endpoints.get_usages_by_node_collections import GetUsagesByNodeCollections
from edu_sharing_client.api.usagev1_api_endpoints.set_usage import SetUsage


class USAGEV1Api(
    DeleteUsage,
    GetUsages,
    GetUsages1,
    GetUsagesByCourse,
    GetUsagesByNode,
    GetUsagesByNodeCollections,
    SetUsage,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
