# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.toolv1_api import TOOLV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestTOOLV1Api(ApiTestMixin, unittest.TestCase):
    """TOOLV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = TOOLV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tool_defintition(self):
        """Test case for create_tool_defintition

        Create a new tool definition object.  # noqa: E501
        """
        from edu_sharing_client.api.toolv1_api_endpoints import create_tool_defintition as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_create_tool_instance(self):
        """Test case for create_tool_instance

        Create a new tool Instance object.  # noqa: E501
        """
        from edu_sharing_client.api.toolv1_api_endpoints import create_tool_instance as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_create_tool_object(self):
        """Test case for create_tool_object

        Create a new tool object for a given tool instance.  # noqa: E501
        """
        from edu_sharing_client.api.toolv1_api_endpoints import create_tool_object as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_get_all_tool_definitions(self):
        """Test case for get_all_tool_definitions

        Get all ToolDefinitions.  # noqa: E501
        """
        from edu_sharing_client.api.toolv1_api_endpoints import get_all_tool_definitions as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_instance(self):
        """Test case for get_instance

        Get Instances of a ToolDefinition.  # noqa: E501
        """
        from edu_sharing_client.api.toolv1_api_endpoints import get_instance as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_instances(self):
        """Test case for get_instances

        Get Instances of a ToolDefinition.  # noqa: E501
        """
        from edu_sharing_client.api.toolv1_api_endpoints import get_instances as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
