# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.archivev1_api import ARCHIVEV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestARCHIVEV1Api(ApiTestMixin, unittest.TestCase):
    """ARCHIVEV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = ARCHIVEV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_purge(self):
        """Test case for purge

        Searches for archive nodes.  # noqa: E501
        """
        from edu_sharing_client.api.archivev1_api_endpoints import purge as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_restore(self):
        """Test case for restore

        restore archived nodes.  # noqa: E501
        """
        from edu_sharing_client.api.archivev1_api_endpoints import restore as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search_archive(self):
        """Test case for search_archive

        Searches for archive nodes.  # noqa: E501
        """
        from edu_sharing_client.api.archivev1_api_endpoints import search_archive as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search_archive_person(self):
        """Test case for search_archive_person

        Searches for archive nodes.  # noqa: E501
        """
        from edu_sharing_client.api.archivev1_api_endpoints import search_archive_person as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
