# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import edu_sharing_client
from edu_sharing_client.model.config_workflow import ConfigWorkflow
from edu_sharing_client import configuration


class TestConfigWorkflow(unittest.TestCase):
    """ConfigWorkflow unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
