# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.usagev1_api import USAGEV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestUSAGEV1Api(ApiTestMixin, unittest.TestCase):
    """USAGEV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = USAGEV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_usage(self):
        """Test case for delete_usage

        Delete an usage of a node.  # noqa: E501
        """
        from edu_sharing_client.api.usagev1_api_endpoints import delete_usage as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_usages(self):
        """Test case for get_usages

        Get all usages of an application.  # noqa: E501
        """
        from edu_sharing_client.api.usagev1_api_endpoints import get_usages as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_usages1(self):
        """Test case for get_usages1

        """
        from edu_sharing_client.api.usagev1_api_endpoints import get_usages1 as endpoint_module
        response_status = 0
        # TODO get response content working
        pass

    def test_get_usages_by_course(self):
        """Test case for get_usages_by_course

        Get all usages of an course.  # noqa: E501
        """
        from edu_sharing_client.api.usagev1_api_endpoints import get_usages_by_course as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_usages_by_node(self):
        """Test case for get_usages_by_node

        Get all usages of an node.  # noqa: E501
        """
        from edu_sharing_client.api.usagev1_api_endpoints import get_usages_by_node as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_usages_by_node_collections(self):
        """Test case for get_usages_by_node_collections

        Get all collections where this node is used.  # noqa: E501
        """
        from edu_sharing_client.api.usagev1_api_endpoints import get_usages_by_node_collections as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_set_usage(self):
        """Test case for set_usage

        Set a usage for a node. app signature headers and authenticated user required.  # noqa: E501
        """
        from edu_sharing_client.api.usagev1_api_endpoints import set_usage as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'




if __name__ == '__main__':
    unittest.main()
