# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.commentv1_api import COMMENTV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestCOMMENTV1Api(ApiTestMixin, unittest.TestCase):
    """COMMENTV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = COMMENTV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_add_comment(self):
        """Test case for add_comment

        create a new comment  # noqa: E501
        """
        from edu_sharing_client.api.commentv1_api_endpoints import add_comment as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_delete_comment(self):
        """Test case for delete_comment

        delete a comment  # noqa: E501
        """
        from edu_sharing_client.api.commentv1_api_endpoints import delete_comment as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_edit_comment(self):
        """Test case for edit_comment

        edit a comment  # noqa: E501
        """
        from edu_sharing_client.api.commentv1_api_endpoints import edit_comment as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_get_comments(self):
        """Test case for get_comments

        list comments  # noqa: E501
        """
        from edu_sharing_client.api.commentv1_api_endpoints import get_comments as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
