# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.mediacenterv1_api import MEDIACENTERV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestMEDIACENTERV1Api(ApiTestMixin, unittest.TestCase):
    """MEDIACENTERV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = MEDIACENTERV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_add_mediacenter_group(self):
        """Test case for add_mediacenter_group

        add a group that is managed by the given mediacenter  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import add_mediacenter_group as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_create_mediacenter(self):
        """Test case for create_mediacenter

        create new mediacenter in repository.  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import create_mediacenter as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_delete_mediacenter(self):
        """Test case for delete_mediacenter

        delete a mediacenter group and it's admin group and proxy group  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import delete_mediacenter as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_edit_mediacenter(self):
        """Test case for edit_mediacenter

        edit a mediacenter in repository.  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import edit_mediacenter as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_get_mediacenter_groups(self):
        """Test case for get_mediacenter_groups

        get groups that are managed by the given mediacenter  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import get_mediacenter_groups as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_mediacenter_licensed_nodes(self):
        """Test case for get_mediacenter_licensed_nodes

        get nodes that are licensed by the given mediacenter  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import get_mediacenter_licensed_nodes as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_get_mediacenters(self):
        """Test case for get_mediacenters

        get mediacenters in the repository.  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import get_mediacenters as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_import_mc_org_connections(self):
        """Test case for import_mc_org_connections

        Import Mediacenter Organisation Connection  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import import_mc_org_connections as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_import_mediacenters(self):
        """Test case for import_mediacenters

        Import mediacenters  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import import_mediacenters as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_import_organisations(self):
        """Test case for import_organisations

        Import Organisations  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import import_organisations as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_remove_mediacenter_group(self):
        """Test case for remove_mediacenter_group

        delete a group that is managed by the given mediacenter  # noqa: E501
        """
        from edu_sharing_client.api.mediacenterv1_api_endpoints import remove_mediacenter_group as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
