# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.ratingv1_api import RATINGV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestRATINGV1Api(ApiTestMixin, unittest.TestCase):
    """RATINGV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = RATINGV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_add_or_update_rating(self):
        """Test case for add_or_update_rating

        create or update a rating  # noqa: E501
        """
        from edu_sharing_client.api.ratingv1_api_endpoints import add_or_update_rating as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_delete_rating(self):
        """Test case for delete_rating

        delete a comment  # noqa: E501
        """
        from edu_sharing_client.api.ratingv1_api_endpoints import delete_rating as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
