# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.mdsv1_api import MDSV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestMDSV1Api(ApiTestMixin, unittest.TestCase):
    """MDSV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = MDSV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_metadata_set(self):
        """Test case for get_metadata_set

        Get metadata set new.  # noqa: E501
        """
        from edu_sharing_client.api.mdsv1_api_endpoints import get_metadata_set as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_metadata_sets(self):
        """Test case for get_metadata_sets

        Get metadata sets V2 of repository.  # noqa: E501
        """
        from edu_sharing_client.api.mdsv1_api_endpoints import get_metadata_sets as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_values(self):
        """Test case for get_values

        Get values.  # noqa: E501
        """
        from edu_sharing_client.api.mdsv1_api_endpoints import get_values as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_get_values4_keys(self):
        """Test case for get_values4_keys

        Get values for keys.  # noqa: E501
        """
        from edu_sharing_client.api.mdsv1_api_endpoints import get_values4_keys as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_suggest_value(self):
        """Test case for suggest_value

        Suggest a value.  # noqa: E501
        """
        from edu_sharing_client.api.mdsv1_api_endpoints import suggest_value as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
