# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.trackingv1_api import TRACKINGV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestTRACKINGV1Api(ApiTestMixin, unittest.TestCase):
    """TRACKINGV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = TRACKINGV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_track_event(self):
        """Test case for track_event

        Track a user interaction  # noqa: E501
        """
        from edu_sharing_client.api.trackingv1_api_endpoints import track_event as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
