# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.sharingv1_api import SHARINGV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestSHARINGV1Api(ApiTestMixin, unittest.TestCase):
    """SHARINGV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = SHARINGV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_children1(self):
        """Test case for get_children1

        Get all children of this share.  # noqa: E501
        """
        from edu_sharing_client.api.sharingv1_api_endpoints import get_children1 as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_info(self):
        """Test case for get_info

        Get general info of a share.  # noqa: E501
        """
        from edu_sharing_client.api.sharingv1_api_endpoints import get_info as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
