# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.knowledgev1_api import KNOWLEDGEV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestKNOWLEDGEV1Api(ApiTestMixin, unittest.TestCase):
    """KNOWLEDGEV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = KNOWLEDGEV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_analyzing_job_status(self):
        """Test case for get_analyzing_job_status

        Get analyzing job status.  # noqa: E501
        """
        from edu_sharing_client.api.knowledgev1_api_endpoints import get_analyzing_job_status as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_run_analyzing_job(self):
        """Test case for run_analyzing_job

        Run analyzing job.  # noqa: E501
        """
        from edu_sharing_client.api.knowledgev1_api_endpoints import run_analyzing_job as endpoint_module
        response_status = 202
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
