# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.authenticationv1_api import AUTHENTICATIONV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestAUTHENTICATIONV1Api(ApiTestMixin, unittest.TestCase):
    """AUTHENTICATIONV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = AUTHENTICATIONV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate(self):
        """Test case for authenticate

        authenticate user of an registered application.  # noqa: E501
        """
        from edu_sharing_client.api.authenticationv1_api_endpoints import authenticate as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_has_access_to_scope(self):
        """Test case for has_access_to_scope

        Returns true if the current user has access to the given scope  # noqa: E501
        """
        from edu_sharing_client.api.authenticationv1_api_endpoints import has_access_to_scope as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_login(self):
        """Test case for login

        Validates the Basic Auth Credentials and check if the session is a logged in user  # noqa: E501
        """
        from edu_sharing_client.api.authenticationv1_api_endpoints import login as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_login_to_scope(self):
        """Test case for login_to_scope

        Validates the Basic Auth Credentials and check if the session is a logged in user  # noqa: E501
        """
        from edu_sharing_client.api.authenticationv1_api_endpoints import login_to_scope as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_logout(self):
        """Test case for logout

        Destroys the current session and logout the user  # noqa: E501
        """
        from edu_sharing_client.api.authenticationv1_api_endpoints import logout as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
