# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.streamv1_api import STREAMV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestSTREAMV1Api(ApiTestMixin, unittest.TestCase):
    """STREAMV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = STREAMV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_add_entry(self):
        """Test case for add_entry

        add a new stream object.  # noqa: E501
        """
        from edu_sharing_client.api.streamv1_api_endpoints import add_entry as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_can_access(self):
        """Test case for can_access

        test  # noqa: E501
        """
        from edu_sharing_client.api.streamv1_api_endpoints import can_access as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_delete_entry(self):
        """Test case for delete_entry

        delete a stream object  # noqa: E501
        """
        from edu_sharing_client.api.streamv1_api_endpoints import delete_entry as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_property_values(self):
        """Test case for get_property_values

        Get top values for a property  # noqa: E501
        """
        from edu_sharing_client.api.streamv1_api_endpoints import get_property_values as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search1(self):
        """Test case for search1

        Get the stream content for the current user with the given status.  # noqa: E501
        """
        from edu_sharing_client.api.streamv1_api_endpoints import search1 as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_update_entry(self):
        """Test case for update_entry

        update status for a stream object and authority  # noqa: E501
        """
        from edu_sharing_client.api.streamv1_api_endpoints import update_entry as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
