# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.iamv1_api import IAMV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestIAMV1Api(ApiTestMixin, unittest.TestCase):
    """IAMV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = IAMV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_add_membership(self):
        """Test case for add_membership

        Add member to the group.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import add_membership as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_add_node_list(self):
        """Test case for add_node_list

        Add a node to node a list of a user  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import add_node_list as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_change_group_profile(self):
        """Test case for change_group_profile

        Set profile of the group.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import change_group_profile as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_change_user_avatar(self):
        """Test case for change_user_avatar

        Set avatar of the user.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import change_user_avatar as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_change_user_password(self):
        """Test case for change_user_password

        Change/Set password of the user.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import change_user_password as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_change_user_profile(self):
        """Test case for change_user_profile

        Set profile of the user.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import change_user_profile as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_confirm_signup(self):
        """Test case for confirm_signup

        put the pending user into the group  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import confirm_signup as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_create_group(self):
        """Test case for create_group

        Create a new group.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import create_group as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_create_user(self):
        """Test case for create_user

        Create a new user.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import create_user as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_delete_group(self):
        """Test case for delete_group

        Delete the group.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import delete_group as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_delete_membership(self):
        """Test case for delete_membership

        Delete member from the group.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import delete_membership as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete the user.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import delete_user as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_group(self):
        """Test case for get_group

        Get the group.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_group as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_membership(self):
        """Test case for get_membership

        Get all members of the group.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_membership as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_node_list(self):
        """Test case for get_node_list

        Get a specific node list for a user  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_node_list as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_preferences(self):
        """Test case for get_preferences

        Get preferences stored for user  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_preferences as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_profile_settings(self):
        """Test case for get_profile_settings

        Get profileSettings configuration  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_profile_settings as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_recently_invited(self):
        """Test case for get_recently_invited

        Get recently invited authorities.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_recently_invited as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_subgroup_by_type(self):
        """Test case for get_subgroup_by_type

        Get a subgroup by the specified type  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_subgroup_by_type as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_user(self):
        """Test case for get_user

        Get the user.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_user as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_user_groups(self):
        """Test case for get_user_groups

        Get all groups the given user is member of.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_user_groups as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_user_stats(self):
        """Test case for get_user_stats

        Get the user stats.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import get_user_stats as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_reject_signup(self):
        """Test case for reject_signup

        reject the pending user  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import reject_signup as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_remove_node_list(self):
        """Test case for remove_node_list

        Deelete a node of a node list of a user  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import remove_node_list as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_remove_user_avatar(self):
        """Test case for remove_user_avatar

        Remove avatar of the user.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import remove_user_avatar as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search_authorities(self):
        """Test case for search_authorities

        Search authorities.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import search_authorities as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search_groups(self):
        """Test case for search_groups

        Search groups.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import search_groups as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search_user(self):
        """Test case for search_user

        Search users.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import search_user as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_set_preferences(self):
        """Test case for set_preferences

        Set preferences for user  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import set_preferences as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_set_profile_settings(self):
        """Test case for set_profile_settings

        Set profileSettings Configuration  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import set_profile_settings as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_signup_group(self):
        """Test case for signup_group

        let the current user signup to the given group  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import signup_group as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_signup_group_details(self):
        """Test case for signup_group_details

         requires admin rights  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import signup_group_details as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_signup_group_list(self):
        """Test case for signup_group_list

        list pending users that want to join this group  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import signup_group_list as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_update_user_status(self):
        """Test case for update_user_status

        update the user status.  # noqa: E501
        """
        from edu_sharing_client.api.iamv1_api_endpoints import update_user_status as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
