# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.renderingv1_api import RENDERINGV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestRENDERINGV1Api(ApiTestMixin, unittest.TestCase):
    """RENDERINGV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = RENDERINGV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_details_snippet(self):
        """Test case for get_details_snippet

        Get metadata of node.  # noqa: E501
        """
        from edu_sharing_client.api.renderingv1_api_endpoints import get_details_snippet as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_details_snippet_with_parameters(self):
        """Test case for get_details_snippet_with_parameters

        Get metadata of node.  # noqa: E501
        """
        from edu_sharing_client.api.renderingv1_api_endpoints import get_details_snippet_with_parameters as endpoint_module
        response_status = 200
        # TODO get response content working


if __name__ == '__main__':
    unittest.main()
