# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.networkv1_api import NETWORKV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestNETWORKV1Api(ApiTestMixin, unittest.TestCase):
    """NETWORKV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = NETWORKV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_add_service(self):
        """Test case for add_service

        Register service.  # noqa: E501
        """
        from edu_sharing_client.api.networkv1_api_endpoints import add_service as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_get_repositories(self):
        """Test case for get_repositories

        Get repositories.  # noqa: E501
        """
        from edu_sharing_client.api.networkv1_api_endpoints import get_repositories as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_service(self):
        """Test case for get_service

        Get own service.  # noqa: E501
        """
        from edu_sharing_client.api.networkv1_api_endpoints import get_service as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_services(self):
        """Test case for get_services

        Get services.  # noqa: E501
        """
        from edu_sharing_client.api.networkv1_api_endpoints import get_services as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_update_service(self):
        """Test case for update_service

        Update a service.  # noqa: E501
        """
        from edu_sharing_client.api.networkv1_api_endpoints import update_service as endpoint_module
        response_status = 200
        # TODO get response content working


if __name__ == '__main__':
    unittest.main()
