# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.adminv1_api import ADMINV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestADMINV1Api(ApiTestMixin, unittest.TestCase):
    """ADMINV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = ADMINV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_add_application(self):
        """Test case for add_application

        register/add an application via xml file  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import add_application as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_add_application1(self):
        """Test case for add_application1

        register/add an application  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import add_application1 as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_add_toolpermission(self):
        """Test case for add_toolpermission

        add a new toolpermissions  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import add_toolpermission as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_apply_template(self):
        """Test case for apply_template

        apply a folder template  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import apply_template as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_cancel_job(self):
        """Test case for cancel_job

        cancel a running job  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import cancel_job as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_change_logging(self):
        """Test case for change_logging

        Change the loglevel for classes at runtime.  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import change_logging as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_clear_cache(self):
        """Test case for clear_cache

        clear cache  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import clear_cache as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_delete_person(self):
        """Test case for delete_person

        delete persons  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import delete_person as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_export_by_lucene(self):
        """Test case for export_by_lucene

        Search for custom lucene query and choose specific properties to load  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import export_by_lucene as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_export_lom(self):
        """Test case for export_lom

        Export Nodes with LOM Metadata Format  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import export_lom as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_all_jobs(self):
        """Test case for get_all_jobs

        get all available jobs  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_all_jobs as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_all_toolpermissions(self):
        """Test case for get_all_toolpermissions

        get all toolpermissions for an authority  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_all_toolpermissions as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_application_xml(self):
        """Test case for get_application_xml

        list any xml properties (like from homeApplication.properties.xml)  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_application_xml as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_applications(self):
        """Test case for get_applications

        list applications  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_applications as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_cache_entries(self):
        """Test case for get_cache_entries

        Get entries of a cache  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_cache_entries as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_cache_info(self):
        """Test case for get_cache_info

        Get information about a cache  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_cache_info as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_catalina_out(self):
        """Test case for get_catalina_out

        Get last info from catalina out  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_catalina_out as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_cluster(self):
        """Test case for get_cluster

        Get information about the Cluster  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_cluster as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_clusters(self):
        """Test case for get_clusters

        Get information about the Cluster  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_clusters as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_config(self):
        """Test case for get_config

        get the repository config object  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_config as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_config_file(self):
        """Test case for get_config_file

        get a base system config file (e.g. edu-sharing.conf)  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_config_file as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_global_groups(self):
        """Test case for get_global_groups

        Get global groups  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_global_groups as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_jobs(self):
        """Test case for get_jobs

        get all running jobs  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_jobs as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_lightbend_config(self):
        """Test case for get_lightbend_config

        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_lightbend_config as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_oai_classes(self):
        """Test case for get_oai_classes

        Get OAI class names  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_oai_classes as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_property_to_mds(self):
        """Test case for get_property_to_mds

        Get a Mds Valuespace for all values of the given properties  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_property_to_mds as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_statistics(self):
        """Test case for get_statistics

        get statistics  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import get_statistics as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_import_collections(self):
        """Test case for import_collections

        import collections via a xml file  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import import_collections as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_import_excel(self):
        """Test case for import_excel

        Import excel data  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import import_excel as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_import_oai(self):
        """Test case for import_oai

        Import oai data  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import import_oai as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_import_oai_xml(self):
        """Test case for import_oai_xml

        Import single xml via oai (for testing)  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import import_oai_xml as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_refresh_app_info(self):
        """Test case for refresh_app_info

        refresh app info  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import refresh_app_info as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_refresh_cache(self):
        """Test case for refresh_cache

        Refresh cache  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import refresh_cache as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_refresh_edu_group_cache(self):
        """Test case for refresh_edu_group_cache

        Refresh the Edu Group Cache  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import refresh_edu_group_cache as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_remove_application(self):
        """Test case for remove_application

        remove an application  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import remove_application as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_remove_cache_entry(self):
        """Test case for remove_cache_entry

        remove cache entry  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import remove_cache_entry as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_remove_oai_imports(self):
        """Test case for remove_oai_imports

        Remove deleted imports  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import remove_oai_imports as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search_by_elastic_dsl(self):
        """Test case for search_by_elastic_dsl

        Search for custom elastic DSL query  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import search_by_elastic_dsl as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_search_by_lucene(self):
        """Test case for search_by_lucene

        Search for custom lucene query  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import search_by_lucene as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_server_update_list(self):
        """Test case for server_update_list

        list available update tasks  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import server_update_list as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_server_update_list1(self):
        """Test case for server_update_list1

        Run an update tasks  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import server_update_list1 as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_set_config(self):
        """Test case for set_config

        set/update the repository config object  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import set_config as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_set_toolpermissions(self):
        """Test case for set_toolpermissions

        set toolpermissions for an authority  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import set_toolpermissions as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_start_job(self):
        """Test case for start_job

        Start a Job.  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import start_job as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_start_job_sync(self):
        """Test case for start_job_sync

        Start a Job.  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import start_job_sync as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_switch_authority(self):
        """Test case for switch_authority

        switch the session to a known authority name  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import switch_authority as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_test_mail(self):
        """Test case for test_mail

        Test a mail template  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import test_mail as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_update_application_xml(self):
        """Test case for update_application_xml

        edit any properties xml (like homeApplication.properties.xml)  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import update_application_xml as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_update_config_file(self):
        """Test case for update_config_file

        update a base system config file (e.g. edu-sharing.conf)  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import update_config_file as endpoint_module
        response_status = 200
        # TODO get response content working

    def test_upload_temp(self):
        """Test case for upload_temp

        Upload a file  # noqa: E501
        """
        from edu_sharing_client.api.adminv1_api_endpoints import upload_temp as endpoint_module
        response_status = 200
        # TODO get response content working


if __name__ == '__main__':
    unittest.main()
