# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.organizationv1_api import ORGANIZATIONV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestORGANIZATIONV1Api(ApiTestMixin, unittest.TestCase):
    """ORGANIZATIONV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = ORGANIZATIONV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_create_organizations(self):
        """Test case for create_organizations

        create organization in repository.  # noqa: E501
        """
        from edu_sharing_client.api.organizationv1_api_endpoints import create_organizations as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_delete_organizations(self):
        """Test case for delete_organizations

        Delete organization of repository.  # noqa: E501
        """
        from edu_sharing_client.api.organizationv1_api_endpoints import delete_organizations as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_organization(self):
        """Test case for get_organization

        Get organization by id.  # noqa: E501
        """
        from edu_sharing_client.api.organizationv1_api_endpoints import get_organization as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_organizations(self):
        """Test case for get_organizations

        Get organizations of repository.  # noqa: E501
        """
        from edu_sharing_client.api.organizationv1_api_endpoints import get_organizations as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_remove_from_organization(self):
        """Test case for remove_from_organization

        Remove member from organization.  # noqa: E501
        """
        from edu_sharing_client.api.organizationv1_api_endpoints import remove_from_organization as endpoint_module
        response_status = 200
        # TODO get response content working
        pass


if __name__ == '__main__':
    unittest.main()
