# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.bulkv1_api import BULKV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestBULKV1Api(ApiTestMixin, unittest.TestCase):
    """BULKV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = BULKV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_find(self):
        """Test case for find

        gets a given node  # noqa: E501
        """
        from edu_sharing_client.api.bulkv1_api_endpoints import find as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'



    def test_sync(self):
        """Test case for sync

        Create or update a given node  # noqa: E501
        """
        from edu_sharing_client.api.bulkv1_api_endpoints import sync as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'




if __name__ == '__main__':
    unittest.main()
