# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import edu_sharing_client
from edu_sharing_client.api.configv1_api import CONFIGV1Api  # noqa: E501
from edu_sharing_client import configuration, schemas, api_client

from . import ApiTestMixin


class TestCONFIGV1Api(ApiTestMixin, unittest.TestCase):
    """CONFIGV1Api unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = CONFIGV1Api(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_config1(self):
        """Test case for get_config1

        get repository config values  # noqa: E501
        """
        from edu_sharing_client.api.configv1_api_endpoints import get_config1 as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_dynamic_value(self):
        """Test case for get_dynamic_value

        Get a config entry (appropriate rights for the entry are required)  # noqa: E501
        """
        from edu_sharing_client.api.configv1_api_endpoints import get_dynamic_value as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_language(self):
        """Test case for get_language

        get override strings for the current language  # noqa: E501
        """
        from edu_sharing_client.api.configv1_api_endpoints import get_language as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_language_defaults(self):
        """Test case for get_language_defaults

        get all inital language strings for angular  # noqa: E501
        """
        from edu_sharing_client.api.configv1_api_endpoints import get_language_defaults as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_get_variables(self):
        """Test case for get_variables

        get global config variables  # noqa: E501
        """
        from edu_sharing_client.api.configv1_api_endpoints import get_variables as endpoint_module
        response_status = 200
        # TODO get response content working
        pass

    def test_set_dynamic_value(self):
        """Test case for set_dynamic_value

        Set a config entry (admin rights required)  # noqa: E501
        """
        from edu_sharing_client.api.configv1_api_endpoints import set_dynamic_value as endpoint_module
        response_status = 200
        # TODO get response content working
        content_type = 'application/json'




if __name__ == '__main__':
    unittest.main()
