# coding: utf-8

# flake8: noqa

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

__version__ = "0.1.0"

# import ApiClient
from edu_sharing_client.api_client import ApiClient

# import Configuration
from edu_sharing_client.configuration import Configuration

# import exceptions
from edu_sharing_client.exceptions import OpenApiException
from edu_sharing_client.exceptions import ApiAttributeError
from edu_sharing_client.exceptions import ApiTypeError
from edu_sharing_client.exceptions import ApiValueError
from edu_sharing_client.exceptions import ApiKeyError
from edu_sharing_client.exceptions import ApiException
